POST http://localhost:8080/loan/decision
Content-Type: application/json

{
  "personalCode": "50307172740",
  "loanAmount": "2000",
  "loanPeriod": "20",
  "age": 20
}
### SEGMENT 1 with high loan amount
POST http://localhost:8080/loan/decision
Content-Type: application/json

{
  "personalCode": "50307172740",
  "loanAmount": "5000",
  "loanPeriod": "24",
  "age": 30
}

### SEGMENT 2 with acceptable loan amount
POST http://localhost:8080/loan/decision
Content-Type: application/json

{
"personalCode": "38411266610",
"loanAmount": "3000",
"loanPeriod": "24"
}

### WIth invalid age
POST http://localhost:8080/loan/decision
Content-Type: application/json

{
"personalCode": "38411266610",
"loanAmount": "3000",
"loanPeriod": "24",
  "age": 69
}